# -*- coding: utf-8 -*-
"""Python Insights - Analisando Dados com Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDgKh2Vf8Xyj4AjGkPEu12nfLYugtsHu
"""

import pandas as pd

tabela = pd.read_csv("cancelamentos_sample.csv")

tabela = tabela.drop(columns="CustomerID")
display(tabela)

display(tabela.info())
tabela = tabela.dropna()

display(tabela.info())

display(tabela["cancelou"].value_counts())

display(tabela["cancelou"].value_counts(normalize=True))

import plotly.express as px


for coluna in tabela.columns:
    grafico = px.histogram(tabela, x=coluna, color="cancelou")
    grafico.show()

tabela = tabela[tabela["duracao_contrato"]!="Monthly"]
tabela = tabela[tabela["ligacoes_callcenter"]<=4]
tabela = tabela[tabela["dias_atraso"]<=20]

display(tabela["cancelou"].value_counts())
display(tabela["cancelou"].value_counts(normalize=True))